name: PowerClans
main: com.ie23s.bukkit.plugin.powerclans.Core
author: ie23s
version: 0.2-ALPHA
depend: [ WorldGuard, WorldEdit ]
commands:
  clan:
    aliases: [ c ]
  powerclans:
    aliases: [ pc ]
permissions:
  PowerClans.*:
    default: op