debug: false
language: ru
database: sqlite # mysql or sqlite
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: admin
settings:
  warm: 2
  max_symbols: 10
  min_symbols: 3
  default_max: 30
  max_upgrade: 50
  #Cost of creating clan. Set 0 to disable.
  create_cost: 0
  #Cost of upgrading clan. Set 0 to disable.
  upgrade_cost: 0
  clan_regex: '[а-яА-Яa-zA-Z0-9]*'
  #The minimum number of players to create a clan house. Set 0 to disable.
  home_min: 0
  #Resolution attacks when enabled PVP WorldGuard. Set 0 to disable or 1 to enable.
  pvp: 1
  #Enabling leader chats
  leader_chat: true
  #Enabling clan chats
  clan_chat: true
  lol: lol
  rf: 4
version_config: 3